# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentEngineStub(object):
    """─── Service Definition ────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Interact = channel.unary_unary(
                '/deepspace.AgentEngine/Interact',
                request_serializer=agent__pb2.InteractRequest.SerializeToString,
                response_deserializer=agent__pb2.InteractResponse.FromString,
                _registered_method=True)
        self.InteractStream = channel.unary_stream(
                '/deepspace.AgentEngine/InteractStream',
                request_serializer=agent__pb2.InteractRequest.SerializeToString,
                response_deserializer=agent__pb2.InteractStreamChunk.FromString,
                _registered_method=True)
        self.Remember = channel.unary_unary(
                '/deepspace.AgentEngine/Remember',
                request_serializer=agent__pb2.RememberRequest.SerializeToString,
                response_deserializer=agent__pb2.RememberResponse.FromString,
                _registered_method=True)
        self.Recall = channel.unary_unary(
                '/deepspace.AgentEngine/Recall',
                request_serializer=agent__pb2.RecallRequest.SerializeToString,
                response_deserializer=agent__pb2.RecallResponse.FromString,
                _registered_method=True)
        self.Consolidate = channel.unary_unary(
                '/deepspace.AgentEngine/Consolidate',
                request_serializer=agent__pb2.ConsolidateRequest.SerializeToString,
                response_deserializer=agent__pb2.ConsolidateResponse.FromString,
                _registered_method=True)
        self.Solve = channel.unary_unary(
                '/deepspace.AgentEngine/Solve',
                request_serializer=agent__pb2.SolveRequest.SerializeToString,
                response_deserializer=agent__pb2.SolveResponse.FromString,
                _registered_method=True)
        self.SolveStream = channel.unary_stream(
                '/deepspace.AgentEngine/SolveStream',
                request_serializer=agent__pb2.SolveRequest.SerializeToString,
                response_deserializer=agent__pb2.SolveStreamChunk.FromString,
                _registered_method=True)
        self.GetAutonomousStatus = channel.unary_unary(
                '/deepspace.AgentEngine/GetAutonomousStatus',
                request_serializer=agent__pb2.AutonomousStatusRequest.SerializeToString,
                response_deserializer=agent__pb2.AutonomousStatusResponse.FromString,
                _registered_method=True)
        self.GetProactiveContext = channel.unary_unary(
                '/deepspace.AgentEngine/GetProactiveContext',
                request_serializer=agent__pb2.ProactiveContextRequest.SerializeToString,
                response_deserializer=agent__pb2.ProactiveContextResponse.FromString,
                _registered_method=True)
        self.GetModelStatus = channel.unary_unary(
                '/deepspace.AgentEngine/GetModelStatus',
                request_serializer=agent__pb2.ModelStatusRequest.SerializeToString,
                response_deserializer=agent__pb2.ModelStatusResponse.FromString,
                _registered_method=True)
        self.SearchGraph = channel.unary_unary(
                '/deepspace.AgentEngine/SearchGraph',
                request_serializer=agent__pb2.GraphSearchRequest.SerializeToString,
                response_deserializer=agent__pb2.GraphSearchResponse.FromString,
                _registered_method=True)
        self.GetNeighbors = channel.unary_unary(
                '/deepspace.AgentEngine/GetNeighbors',
                request_serializer=agent__pb2.NeighborsRequest.SerializeToString,
                response_deserializer=agent__pb2.NeighborsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/deepspace.AgentEngine/Health',
                request_serializer=agent__pb2.HealthRequest.SerializeToString,
                response_deserializer=agent__pb2.HealthResponse.FromString,
                _registered_method=True)


class AgentEngineServicer(object):
    """─── Service Definition ────────────────────────────

    """

    def Interact(self, request, context):
        """Agent interaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InteractStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remember(self, request, context):
        """Memory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consolidate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Solve(self, request, context):
        """Orchestration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SolveStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAutonomousStatus(self, request, context):
        """Autonomous
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProactiveContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelStatus(self, request, context):
        """Model Router
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchGraph(self, request, context):
        """Knowledge Graph
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNeighbors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Interact': grpc.unary_unary_rpc_method_handler(
                    servicer.Interact,
                    request_deserializer=agent__pb2.InteractRequest.FromString,
                    response_serializer=agent__pb2.InteractResponse.SerializeToString,
            ),
            'InteractStream': grpc.unary_stream_rpc_method_handler(
                    servicer.InteractStream,
                    request_deserializer=agent__pb2.InteractRequest.FromString,
                    response_serializer=agent__pb2.InteractStreamChunk.SerializeToString,
            ),
            'Remember': grpc.unary_unary_rpc_method_handler(
                    servicer.Remember,
                    request_deserializer=agent__pb2.RememberRequest.FromString,
                    response_serializer=agent__pb2.RememberResponse.SerializeToString,
            ),
            'Recall': grpc.unary_unary_rpc_method_handler(
                    servicer.Recall,
                    request_deserializer=agent__pb2.RecallRequest.FromString,
                    response_serializer=agent__pb2.RecallResponse.SerializeToString,
            ),
            'Consolidate': grpc.unary_unary_rpc_method_handler(
                    servicer.Consolidate,
                    request_deserializer=agent__pb2.ConsolidateRequest.FromString,
                    response_serializer=agent__pb2.ConsolidateResponse.SerializeToString,
            ),
            'Solve': grpc.unary_unary_rpc_method_handler(
                    servicer.Solve,
                    request_deserializer=agent__pb2.SolveRequest.FromString,
                    response_serializer=agent__pb2.SolveResponse.SerializeToString,
            ),
            'SolveStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SolveStream,
                    request_deserializer=agent__pb2.SolveRequest.FromString,
                    response_serializer=agent__pb2.SolveStreamChunk.SerializeToString,
            ),
            'GetAutonomousStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAutonomousStatus,
                    request_deserializer=agent__pb2.AutonomousStatusRequest.FromString,
                    response_serializer=agent__pb2.AutonomousStatusResponse.SerializeToString,
            ),
            'GetProactiveContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProactiveContext,
                    request_deserializer=agent__pb2.ProactiveContextRequest.FromString,
                    response_serializer=agent__pb2.ProactiveContextResponse.SerializeToString,
            ),
            'GetModelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelStatus,
                    request_deserializer=agent__pb2.ModelStatusRequest.FromString,
                    response_serializer=agent__pb2.ModelStatusResponse.SerializeToString,
            ),
            'SearchGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchGraph,
                    request_deserializer=agent__pb2.GraphSearchRequest.FromString,
                    response_serializer=agent__pb2.GraphSearchResponse.SerializeToString,
            ),
            'GetNeighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNeighbors,
                    request_deserializer=agent__pb2.NeighborsRequest.FromString,
                    response_serializer=agent__pb2.NeighborsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=agent__pb2.HealthRequest.FromString,
                    response_serializer=agent__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'deepspace.AgentEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('deepspace.AgentEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentEngine(object):
    """─── Service Definition ────────────────────────────

    """

    @staticmethod
    def Interact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspace.AgentEngine/Interact',
            agent__pb2.InteractRequest.SerializeToString,
            agent__pb2.InteractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InteractStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/deepspace.AgentEngine/InteractStream',
            agent__pb2.InteractRequest.SerializeToString,
            agent__pb2.InteractStreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspace.AgentEngine/Remember',
            agent__pb2.RememberRequest.SerializeToString,
            agent__pb2.RememberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspace.AgentEngine/Recall',
            agent__pb2.RecallRequest.SerializeToString,
            agent__pb2.RecallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consolidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspace.AgentEngine/Consolidate',
            agent__pb2.ConsolidateRequest.SerializeToString,
            agent__pb2.ConsolidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Solve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspace.AgentEngine/Solve',
            agent__pb2.SolveRequest.SerializeToString,
            agent__pb2.SolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SolveStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/deepspace.AgentEngine/SolveStream',
            agent__pb2.SolveRequest.SerializeToString,
            agent__pb2.SolveStreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAutonomousStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspace.AgentEngine/GetAutonomousStatus',
            agent__pb2.AutonomousStatusRequest.SerializeToString,
            agent__pb2.AutonomousStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProactiveContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspace.AgentEngine/GetProactiveContext',
            agent__pb2.ProactiveContextRequest.SerializeToString,
            agent__pb2.ProactiveContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspace.AgentEngine/GetModelStatus',
            agent__pb2.ModelStatusRequest.SerializeToString,
            agent__pb2.ModelStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspace.AgentEngine/SearchGraph',
            agent__pb2.GraphSearchRequest.SerializeToString,
            agent__pb2.GraphSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNeighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspace.AgentEngine/GetNeighbors',
            agent__pb2.NeighborsRequest.SerializeToString,
            agent__pb2.NeighborsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspace.AgentEngine/Health',
            agent__pb2.HealthRequest.SerializeToString,
            agent__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
